name: dbt_snowflake_project
version: 1.0.0
config-version: 2

profile: dbt_snowflake_project

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_snowflake_power:
    +persist_docs:
      relation: true
      columns: true

    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: view
      +schema: intermediate

    marts:
      +schema: marts
      dims:
        +materialized: view
      facts:
        +materialized: incremental
        +incremental_strategy: merge
        +on_schema_change: sync_all_columns

snapshots:
  dbt_snowflake_power:
    +target_database: DBT_SCHEMA
    +target_schema: SNAPSHOTS
